### ISSUE TITLE
Route host certificate textarea should not trim data

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-console#208]
In the channels modal under routes when you add a host certificate to a route it trims the data on save. Angular does this automatically. We can't trim a cert as PEM certs need a trailing \n to function.

**Comment by bausmeier** [comment]
I just tested this and adding a cert worked for me. I did have to restart the core though for it to take effect.

**Comment by bausmeier** [comment]
Pretty sure this is realted to https://github.com/jembi/openhim-core-js/issues/326.

**Comment by rcrichton** [comment]
Hmm, ok. How are you testing this? What service are you testing against?

I know we have had trouble in the past when adding certificates to clients that the trimming was causing problems. The cert is getting trimmed here but perhaps that's not the real problem.

**Comment by bausmeier** [comment]
I am just sending a request to the OpenHIM from the command line and testing against a little echo server I wrote. Without a cert for the route I just get "Internal server error" as a response, but if I add a cert and restart the core then I get the response I expect.

**Comment by bausmeier** [comment]
Fixed in https://github.com/jembi/openhim-core-js/commit/6f0281038997d6d77cf929181f691476b4bba99d.
