### ISSUE TITLE
Switch from ng-min to ng-annotate

### ISSUE THREAD

**Issue by bausmeier** [jembi/openhim-console#232]
ng-min is deprecated and causing issues with uglify mangling. It looks like switching to ng-annotate will fix the problem.

I have temporarily disabled mangling in #231. Once this issue has been closed we should re-enable it.

**Comment by rcrichton** [comment]
Should be pretty straight forward: "Grunt users can migrate easily by installing grunt-ng-annotate and replacing ngmin with ngAnnotate in their Gruntfile..."

source: https://github.com/olov/ng-annotate#how-does-ng-annotate-compare-to-ngmin
