### ISSUE TITLE
Should not be able to delete contact group if they are linked to a channel alert

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-console#242]
Currently it's possible to delete a contact group even though they are setup as an alert group for a channel. Two options:
1. Don't allow them to be deleted in this case
2. Loop through all channels and remove the contact group as part of the delete process

2 might be nice actually, but trickier.

Imo this is a post 1.1.0 ticket

**Comment by rcrichton** [comment]
I agree post 1.1.
