### ISSUE TITLE
Tasks Text Colour

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-console#254]
The text colour for the "Progress" field cannot be made out when a task is below half way (white on white)

![screen shot 2015-03-12 at 14 49 45](https://cloud.githubusercontent.com/assets/1872071/6617988/37b01a00-c8c7-11e4-9c4e-87035ff15cff.png)

For example, in the above screenshot, the total cannot be made out

**Comment by BMartinos** [comment]
Investigationg this issue i found that the text inst actual white on white but rather not visible. the area for the text to be displayed in is smaller and therefore does not show up. 

To fix this i have changed the text to be percentage based and added another field below to show the completed against the total
