### ISSUE TITLE
Can't add a second group to a channel alert

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-console#275]

**Comment by BMartinos** [comment]
This issue is actually regarding the adding of a 2nd group to the channels alerts. Throws a 'Cannot read property 'indexOf' of null' error and does not allow a group be added

**Comment by BMartinos** [comment]
To replicate this issue: Navigate to Channels -> Alerts.

Starting from no current alerts in channel: Supply any Status range. ( supply percentage optional ). Add groups. You should be able to add more than one at this stage. Save the alert.

Try adding another alert and adding a group. This should produce a "'indexOf' of null" error and the group will not be able to be added.
