### ISSUE TITLE
Build fails after dependency updates

### ISSUE THREAD

**Issue by bausmeier** [jembi/openhim-console#276]
When running `grunt` the `concurrent:dist` task fails with the following error:

```
        Warning: Running "imagemin:dist" (imagemin) task
    Warning: Error: spawn /opt/openhim-console/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT in file app/images/loading.gif Use --force to continue.
```

Based on [this comment](https://github.com/gruntjs/grunt-contrib-imagemin/issues/96#issuecomment-86531779) I install version 0.7.2 of the grunt-contrib-imagemin module and then it works.

Using node v0.12.0.

**Comment by BMartinos** [comment]
Well spotted thanks @bausmeier

**Comment by MattyJ007** [comment]
We no longer use grunt and our latest supported Node versions are 10 and 12
