### ISSUE TITLE
Create Certificate Modal Bugs

### ISSUE THREAD

**Issue by BMartinos** [jembi/openhim-console#286]
Noticed a few small bugs on the create certificate popup modal. 

"focus=true" isnt on the first input box
*Common Name (e.g. server FQDN or YOUR name) - needs a spacing between required star ( * )
Console error when trying to save certificate ( country validation )

**Comment by rcrichton** [comment]
@debonair didn't you fix these in another PR?

**Comment by debonair** [comment]
Yes, this issue can be closed. I fixed these in pull request #291
