### ISSUE TITLE
Contact Groups -> Contact List

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-console#290]
Despite #114 our terminology can still be a bit confusing with regards to users. There are permissions groups on a channel, but then there are also contact groups for alerts and reports, which is something different.

To avoid confusion, should we rename Contact Groups into Contact Lists?

It's probably not a good idea to update the schema at this stage, so this would be a cosmetic change.

**Comment by BMartinos** [comment]
I like the proposed idea of changing the label names from 'Contact Groups' to 'Contact Lists'. This is a quick easy fix to overcome this confusion.

**Comment by rcrichton** [comment]
Yeah, sounds like a good idea to me as well. We can't change the schema unless we bump the major version so a cosmetic change sounds good.
