### ISSUE TITLE
Global UI changes

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-console#294]
Make changes to general UI including the header, footer and body of the console. This is part of the epic #293. These changes should include:

### Header
* Make header stick on scroll
* Keep box-shadow top but make softer
* Keep grey background

### General Changes
* remove box-shadows
* White background - no grey background in content area 
* Dashboard/graph boxes to have margin/padding ( top/bottom 5px )
* sidebar padding - make padding shorter to make sidebar smaller but add some padding to icons
* 'jump to top' to change to neutral grey colour - reduce padding
* Import/Export add dropdown arrow to indicate toggle functionality
* Tasks automatic refresh.
* Channel routes - removes red boxes and show info ( yellow warning ) box to rather inform the user
* update tooltips to show on '?' icon rather than on the label

### Footer
* Keep grey background
* remove box shadow

**Comment by BMartinos** [comment]
Completed in PR #289
