### ISSUE TITLE
When text is typed into a date field the page redirect on a few of our pages with date pickers

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-console#399]

**Comment by BMartinos** [comment]
@rcrichton is this ticket fine to be closed? I think this is has been resolved in PR #406 
https://github.com/jembi/openhim-console/pull/406/commits/5b1cc53710a021a84da9314ab9f1c6e6b03f29d2

**Comment by rcrichton** [comment]
Yup, that's cool. I'l close it.
