### ISSUE TITLE
Make True/False values more user friendly

### ISSUE THREAD

**Issue by hnnesv** [jembi/openhim-console#410]
A lot pages display the options True/False, e.g.

![screen shot 2016-08-11 at 17 16 39](https://cloud.githubusercontent.com/assets/1872071/17593842/874a03ba-5fe7-11e6-9ba1-aba719d270c8.png)

It would be good to use labels that are more user friendly, like Yes/No

**Comment by kaweesi** [comment]
https://github.com/jembi/openhim-console/pull/430
