### ISSUE TITLE
Typo in "OpenHIM core concepts" documentation

### ISSUE THREAD

**Issue by JohanVanZyl** [jembi/openhim-console#452]
> orchestration - this is the execution of a business function that may need to call out to other service endpoint on **_oother_** system. (eg. Enriching a message with a client's unique identifier retrieved from a client registry).
Maybe it should read "...endpoint on another system."?

**Comment by MattyJ007** [comment]
Fixed on our new docs page: http://openhim.org/docs/user-guide/mediators
