### ISSUE TITLE
Login Issue: openhim-console

### ISSUE THREAD

**Issue by kartikdevarakonda** [jembi/openhim-console#481]
Unable to login into openhim-console, even if the OpenHIM-core server up and running. 

![image](https://user-images.githubusercontent.com/22386703/44830870-7f9aaf00-ac13-11e8-8ace-6970f781db82.png)

Core and Console have been setup in the same windows server. We are unable to notice any errors in the log files. 

Could anyone please help me on this ?

**Comment by Rajneshwar** [comment]
Hi,
   I'am also getting the error below. 
![image](https://user-images.githubusercontent.com/4369014/60305510-d76b8900-9990-11e9-8510-056d5ded3f13.png)
Can someone tell me which exact file goes in the C:\Openhim\Console Folder as I don't see any files/folders such as heartbeat or authenticate as well. I have unzipped contents from this folder by the way: openhim-console-v1.13.0.tar

**Comment by Zooloo2014** [comment]
Hi Rajneshwar

The first thing to check is that the console is pointing to a running instance of the Openhim Core. 
The config for that is in: app/config/default.json

Second, if you're running locally using a self-signed certificate, you need to click the link ('link' in blue in the text) to add an exception in your browser. 
This process is also mentioned in this setup video on [Youtube](https://youtu.be/DUr_mBWIVXk)
 
---
> Hi,
> I'am also getting the error below.
> ![image](https://user-images.githubusercontent.com/4369014/60305510-d76b8900-9990-11e9-8510-056d5ded3f13.png)
> Can someone tell me which exact file goes in the C:\Openhim\Console Folder as I don't see any files/folders such as heartbeat or authenticate as well. I have unzipped contents from this folder by the way: openhim-console-v1.13.0.tar

**Comment by MattyJ007** [comment]
This topic is covered in our documentation as well http://openhim.org/docs/getting-started/install
