### ISSUE TITLE
how to get OpenHIM to work behind NGINX

### ISSUE THREAD

**Issue by jayrichtz** [jembi/openhim-console#503]
Hi,
I have been having challenge on how to get OpenHim to work behind NGINX server, i can access console page but issue is accessing OpenHim Core using certificate in OpenHim local server.

so my connection is designed in a such a way that i have Vmware for Nginx which act as server for forwarding requests to local VMs, OpenHim VM is not exposed to internet. 
thanks,
John 
![openhim](https://user-images.githubusercontent.com/47076132/59501854-197ed000-8ea5-11e9-9adb-a77f636516de.PNG)

**Comment by MattyJ007** [comment]
Hi John, this issue is due to the OpenHIM's self-signed certificates. This topic is covered in our documentation - http://openhim.org/docs/getting-started/install

I'm closing this issue but if this was not the issue please respond here and provide more information.
