### ISSUE TITLE
Issues linking openhim-console to openhim-core

### ISSUE THREAD

**Issue by cozej4** [jembi/openhim-console#525]
I have installed the openhim core and openhim-console using the documentation found [here](http://openhim.org/docs/installation/npm)

I have updated the openhim config/default.json file with the host name address of the openhim-core which is not running on the same machine.

But opening the Admin console and trying to login using the default password am presented with an error message and on further inspection on the browsers developer console, I see that the console is trying to access the openhim-core via https://localhost:8080 even though this has been updated in default.json host to point to the correct address.

How can I fix this issue?

<img width="1680" alt="Screen Shot 2020-07-23 at 10 38 33 PM" src="https://user-images.githubusercontent.com/9714534/88331306-6b935580-cd35-11ea-8831-e77b807d19e5.png">
<img width="1680" alt="Screen Shot 2020-07-23 at 10 39 27 PM" src="https://user-images.githubusercontent.com/9714534/88331325-73eb9080-cd35-11ea-917d-b76eebf7e414.png">

**Comment by BMartinos** [comment]
Hi @cozej4 

Did you end up coming right with the issue you were having or still experiencing the same issue?

**Comment by cozej4** [comment]
Hi @BMartinos 

Yes, I did find the fix to the issue. 
In my case this was an apache2 issue that was causing this weird behavior. After trying to use Nginx instead of Apache2, everything works correctly as intended.
I am not sure why this is the case while using Apache2 and not NginX. But for now this is resolved.

**Comment by BMartinos** [comment]
Hi @cozej4 

Ok great, glad that you managed to get it working. I think the issue might have been that the web page was being cached and still had the older config details stored. By switching out apache for Nginx it will have used a fresh copy of the console to serve to the browser

**Comment by cozej4** [comment]
@BMartinos 

Yes that makes perfect sense. That could explain why I was experiencing the weird behaviour. 
Thank you for the clarification.
