### ISSUE TITLE
how to configure docker-compose to use domain name instead of localhost

### ISSUE THREAD

**Issue by satyadeep-ih** [jembi/openhim-console#615]
Hi, 

I pulled docker-compose.yml from [https://github.com/jembi/openhim-core-js/blob/master/infrastructure/docker-compose.yml](url), and the docker containers are up, however when I am hitting my-domain:9000 , it is giving error while trying to connect to https://localhost:8080 and this is working fine when I am hitting my-domain:8080. Can someone suggest me how to change this localhost to my-domain as I do not see this in docker-compose.yml 

Thanks
![admin-console-openhim](https://github.com/jembi/openhim-console/assets/74664078/49371e41-7757-420f-a19f-7cae43ebfc38)

![working-correctly-with-domain-name](https://github.com/jembi/openhim-console/assets/74664078/148e0c68-2756-4d4a-9952-a7198544cf9a)
![not-working-with-localhost](https://github.com/jembi/openhim-console/assets/74664078/61a3cd55-df52-49a8-9ec1-b60d72af65fc)

My domain is `revamp.intelehealth.org`

**Comment by arran-standish** [comment]
Under the openhim-console section of the compose file, you can add an environment section to override the two environment variables:
- OPENHIM_CORE_MEDIATOR_HOSTNAME=revamp.intelehealth.org
- OPENHIM_MEDIATOR_API_PORT=8080

Which will then have the frontend try and route to your domain instead of localhost

**Comment by satyadeep-ih** [comment]
After adding environment section this started working, however the default login is giving Credentials incorrect? Any idea why?
