### ISSUE TITLE
Transaction Details not loading Body 

### ISSUE THREAD

**Issue by LarryMatrix** [jembi/openhim-console#659]
I am currently experiencing an issue when viewing transaction details page, I get a page which obviously shows that error comes from angular-highlights package.

<img width="1494" alt="Screenshot 2024-08-15 at 20 18 13" src="https://github.com/user-attachments/assets/181a7964-b752-407b-b8f8-4df9f13b746d">

**Comment by rcrichton** [comment]
Hmm, I haven't seen this one before. Does it happen on very transaction or only certain ones? If you try clear browser cache and reload the page does it help at all? Which version of console are you running?

**Comment by LarryMatrix** [comment]
I am running Console v1.18.2 and Core v8.4.2 as shown in an image below. I tried to even clone a new repository still had the same issue. I thought maybe is my Node version.
I am currently running Node v20.14.0 and Npm v10.7.0

But tried with:
- Node v12.17.0 and Npm v6.14.4
- Node v8.17.0 and Npm v6.13.4
- Node v18.20.3 and Npm v10.7.0

All these versions have the same result. All other functionalities are functioning well but not on the Transaction Details page with that error.

<img width="463" alt="Screenshot 2024-08-16 at 14 07 56" src="https://github.com/user-attachments/assets/28c9e9a5-0d84-4234-91d5-6dd73f589bb3">

**Comment by LarryMatrix** [comment]
Thanks a lot @rcrichton for contribution. I have resolved the issue already, I was experiencing an issue because of the deletion implementation on transactions and rabbit-mq integration I added.

<img width="631" alt="Screenshot 2024-08-16 at 18 07 04" src="https://github.com/user-attachments/assets/7d33b718-bec2-4be7-8dac-38ac5bab0a20">
